#!/bin/bash

cd ~/certs

gnome-terminal --title="VPN" -- \
sudo openconnect -v \
	 -u blazej.michalik@nokia.com \
	 -k michalik.ipa.nsn-net.net.key \
	 -c michalik.ipa.nsn-net.net.crt \
	 --no-proxy \
     cloudnra-fra-emea.net.nokia.com/EE-Linux
	 #nra-emea-fi-esp-vip.net.nokia.com
